apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  annotations:
    meta.helm.sh/release-name: jenkins-operator
    meta.helm.sh/release-namespace: integration
  labels:
    app.kubernetes.io/managed-by: Helm
  name: jenkins
  namespace: integration
spec:
  configurationAsCode:
    configurations: 
    - name: jenkins-operator-user-configuration
  backup:
    action:
      exec:
        command:
        - /home/user/bin/backup.sh
    containerName: backup
    interval: 30
    makeBackupBeforePodDeletion: true
  restore:
    action:
      exec:
        command:
        - /home/user/bin/restore.sh
    containerName: backup
  jenkinsAPISettings:
    authorizationStrategy: createUser
  master:
    basePlugins:
    - name: kubernetes
      version: 1.25.2
    - name: workflow-job
      version: "2.39"
    - name: workflow-aggregator
      version: "2.6"
    - name: git
      version: 4.2.2
    - name: job-dsl
      version: "1.77"
    - name: configuration-as-code
      version: "1.38"
    - name: kubernetes-credentials-provider
      version: "0.13"
    containers:
    - command:
      - bash
      - -c
      - /var/jenkins/scripts/init.sh && exec /sbin/tini -s -- /usr/local/bin/jenkins.sh
      env:
      - name: JAVA_OPTS
        value: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1
          -Djenkins.install.runSetupWizard=false -Djava.awt.headless=true
      image: jenkins/jenkins:lts
      imagePullPolicy: Always
      livenessProbe:
        failureThreshold: 30
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 160
        periodSeconds: 20
        successThreshold: 1
        timeoutSeconds: 5
      name: jenkins-master
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 30
        periodSeconds: 20
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 1500m
          memory: 3Gi
        requests:
          cpu: "1"
          memory: 500Mi
    - env:
      - name: BACKUP_DIR
        value: /backup
      - name: JENKINS_HOME
        value: /jenkins-home
      - name: BACKUP_COUNT
        value: "2"
      image: virtuslab/jenkins-operator-backup-pvc:v0.0.8
      imagePullPolicy: IfNotPresent
      name: backup
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
        requests:
          cpu: 50m
          memory: 50Mi
      volumeMounts:
      - mountPath: /jenkins-home
        name: jenkins-home
      - mountPath: /backup
        name: backup
      - mountPath: /home/user/bin2
        name: custom-backup
    disableCSRFProtection: false
    plugins:
    - name: maven-plugin
      version: "3.8"
    - name: ansible
      version: "1.1"
    #- name: bitbucket
    #  version: 1.1.27
    #- name: bitbucket-build-status-notifier
    #  version: 1.4.2
    - name: docker-plugin
      version: 1.2.1
    #- name: generic-webhook-trigger
    #  version: "1.72"
    #- name: github-pullrequest
    #  version: 0.2.8
    - name: job-import-plugin
      version: "3.4"
    #- name: msbuild
    #  version: "1.29"
    - name: nexus-artifact-uploader
      version: "2.13"
    - name: pipeline-npm
      version: 0.9.2
    - name: pipeline-utility-steps
      version: 2.6.1
    - name: pollscm
      version: 1.3.1
    #- name: postbuild-task
    #  version: "1.9"
    #- name: ranorex-integration
    #  version: 1.0.2
    #- name: sidebar-link
    #  version: 1.11.0
    #- name: sonarqube-generic-coverage
    #  version: "1.0"
    - name: sonar
      version: "2.13"
    #- name: simple-theme-plugin
    #  version: "0.6"
    securityContext:
      fsGroup: 1000
      runAsUser: 1000
    volumes:
    - name: backup
      persistentVolumeClaim:
        claimName: jenkins-backup
    - configMap:
        defaultMode: 0751
        name: custom-backup-cm
      name: custom-backup
  seedJobs:
  - description: Jenkins Operator repository
    id: jenkins-operator
    credentialType: usernamePassword
    credentialID: gitlab-user-jenkins
    repositoryBranch: master
    repositoryUrl: http://gitlab-webservice-default.git-system:8181/devops/jenkins-jobs-as-code.git
    targets: cicd/jobs/*.jenkins
  service:
    port: 8080
    type: ClusterIP
  slaveService:
    port: 50000
    type: ClusterIP
status: {}
