apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  annotations:
    meta.helm.sh/release-name: jenkins-operator
    meta.helm.sh/release-namespace: integration
  labels:
    app.kubernetes.io/managed-by: Helm
  name: jenkins
  namespace: integration
spec:
  configurationAsCode:
    configurations: []
 #   - name: jenkins-operator-user-configuration
  backup:
    action:
      exec:
        command:
        - /home/user/bin/backup.sh
    containerName: backup
    interval: 30
    makeBackupBeforePodDeletion: true
  restore:
    action:
      exec:
        command:
        - /home/user/bin/restore.sh
    containerName: backup
  jenkinsAPISettings:
    authorizationStrategy: createUser
  master:
    containers:
    - command:
      - bash
      - -c
      - /var/jenkins/scripts/init.sh && exec /sbin/tini -s -- /usr/local/bin/jenkins.sh
      env:
      - name: JAVA_OPTS
        value: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1
          -Djenkins.install.runSetupWizard=false -Djava.awt.headless=true
      image: jenkins/jenkins:2.289.1-lts-alpine
      imagePullPolicy: Always
      livenessProbe:
        failureThreshold: 30
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 160
        periodSeconds: 20
        successThreshold: 1
        timeoutSeconds: 5
      name: jenkins-master
      readinessProbe:
        failureThreshold: 20
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 30
        periodSeconds: 20
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 1500m
          memory: 3Gi
        requests:
          cpu: "1"
          memory: 500Mi
    - env:
      - name: BACKUP_DIR
        value: /backup
      - name: JENKINS_HOME
        value: /jenkins-home
      - name: BACKUP_COUNT
        value: "2"
      image: virtuslab/jenkins-operator-backup-pvc:v0.1.0
      imagePullPolicy: IfNotPresent
      name: backup
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
        requests:
          cpu: 50m
          memory: 50Mi
      volumeMounts:
      - mountPath: /jenkins-home
        name: jenkins-home
      - mountPath: /backup
        name: backup
    disableCSRFProtection: false
    securityContext:
      fsGroup: 1000
      runAsUser: 1000
    volumes:
    - name: backup
      persistentVolumeClaim:
        claimName: jenkins-backup
  service:
    port: 8080
    type: ClusterIP
  slaveService:
    port: 50000
    type: ClusterIP
status: {}
