apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: webservice
    app.kubernetes.io/managed-by: Helm
    chart: webservice-4.7.4
    gitlab.com/webservice-name: default
    heritage: Helm
    release: gitlab
  name: gitlab-nodeport
  namespace: git-system
spec:
  ports:
  - port: 8181
    protocol: TCP
    targetPort: 8181
    nodePort: 32041
  selector:
    app: webservice
    gitlab.com/webservice-name: default
    release: gitlab
  type: NodePort
status:
  loadBalancer: {}
