pipeline {
    agent any

    stages {
        stage('mirroring') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'gitlab-devops', passwordVariable: 'password', usernameVariable: 'username')])
               { 
                sh'''
                     mirroring-github-gitlab/mirroring.sh git@github.com:$source  https://$username:$password@gitlab.devops.cdg.com/$destination
                '''
               }
            }
        }
    }
}
